# SQLite poyom
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: test
  username: root
  password: poyom
  host: localhost

production:
  <<: *default
  database: test_production
  username: root
  password: poyom
  host: localhost

